#!/usr/bin/env bash
# Init
FILE="/tmp/out.$$"
GREP="/bin/grep"

#....
# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root!" 1>&2
   exit 1
fi

echo "Stopping ntp..." 
service ntp stop

echo "Manually synchronizing clock with ntpdate..." 
ntpdate `perl -ane 'print "$F[1] " if $F[0] eq "server";' /etc/ntp.conf`

echo "Starting ntp..." 
service ntp start
echo "Finished" 
